version: '3.4'

services:
  xttsapiserver:
    image: xttsapiserver
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8020:8020"
    volumes:
      - ./tts-models:/root/.local/share/tts:rw
